### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by frolic** [holic/web3-scaffold#1]
- [ ] Run through setup process and write a setup guide
- [x] Move common eslint stuff for TS to root or subpackage
- [x] Compile TS for imported packages (just contracts for now I think?) and rip out the webpack TS build step. This should make it easier to replace Next.js with something else.
- [ ] Consider moving to Prettier -> eslint, rather than eslint -> Prettier. This will make it easier to autoformat things that eslint doesn't support but prettier does (CSS, SVG, HTML, etc.)
- [ ] Make sure packages put files in the right place (e.g. contracts ABI -> subgraph ABI) or can generate their own from dependency/import
- [x] Consider removing/ignoring contracts `artifacts` and `typechain-types`

**Comment by frolic** [comment]
While watching CJ:
- [ ] contracts: conditionally use config based on vars in env (e.g. don't use gas reporter if no etherscan API key)
- [x] contracts: rename env vars to use `*_RPC_URL` instead of just `*_URL`
- [x] contracts: fix deploy scripts, needs a double dash `npm run deploy -- --network mumbai`
- [x] app: fix contracts dep name

**Comment by cjpais** [comment]
- [ ] quick documentation about urql
- [ ] note that through the usage of tailwind, html comes unstyled
- [ ] .env in .gitignore?

**Comment by frolic** [comment]
- [x] eslint issue can be fixed like: https://github.com/holic/chirp-city/commit/26e0316228f9ee3edd7a83b15ba1ddbe63257a2d

**Comment by frolic** [comment]
- [ ] add solidity linter/autoformatter

**Comment by frolic** [comment]
- [ ] check that we're getting linting for things like useEffect deps in next.js

**Comment by frolic** [comment]
closing in favor of individual issues
