### ISSUE TITLE
Errors in console when ENS is not supported on chain

### ISSUE THREAD

**Issue by davisshaver** [holic/web3-scaffold#25]
When in local dev, an error shows up if the chain doesn't support ENS. This issue stems from RainbowKit and can be tracked here https://github.com/rainbow-me/rainbowkit/discussions/429.

Example error:

```
next-dev.js?d62b:32 Error: network does not support ENS (operation="ENS", network="foundry", code=UNSUPPORTED_OPERATION, version=providers/5.5.2)
```

**Comment by frolic** [comment]
Looks like this could/should be resolved in https://github.com/rainbow-me/rainbowkit/pull/496?

**Comment by davisshaver** [comment]
The change in https://github.com/holic/web3-scaffold/commit/b552972c4f4f91790f636b3b1324e6405dc69685 addresses this error 🎉
