### ISSUE TITLE
Had troubles deploying new contracts

### ISSUE THREAD

**Issue by BruceWangyq** [holic/web3-scaffold#53]
I followed the doc you wrote. But when I tried to change the minting price in ExampleNFT.sol from 0.1 to 0.01 ether, I ran the [http://deploy.sh](https://t.co/fL7ABTJlgb) it only gives me "Using goerli contract address: 0xe584409f2ba1ade9895485d90587fd46baa3c0d8" over and over again, even if I tried to write a new contract. I had set up the local env. 

(Thanks to the reply from @TheRightChoyce: I need to delete the packages/contracts/deploys/goerli/ExampleNFT.json and run the ./deploy.sh in packages/contracts to deploy a new contract before trying to redeploy the new contract, otherwise the shell script will exit and just print the existing contact info. Now I can deploy new contracts. Thanks to him)

**Comment by frolic** [comment]
Sounds like this is resolved, so I'm closing
